export const featPortfolio = {
  coverImg: "https://imgur.com/WNmG3Q6.jpg",
  alt: "default portfolio image",
  heading: "Feat Portfolio",
  body: "Lorem ipsum dolor sit amet, word and some adipiscing elit. Lorem ipsum dolor sit amet, word and some adipiscing elit.",
  gitHubLink: "https://github.com/jaminwebdev",
  readMore: "https://google.com",
  view: "https://google.com",
  svg: true,
  icons: ["nuxt", "node", "postgres"],
}

export const portfolios = [
  {
    coverImg: "https://imgur.com/WNmG3Q6.jpg",
    alt: "default portfolio image",
    heading: "Sadie's Faves",
    body: "Lorem ipsum dolor sit amet, word and some adipiscing elit. Lorem ipsum dolor sit amet, word and some adipiscing elit.",
    gitHubLink: "https://github.com/jaminwebdev",
    readMore: "https://google.com",
    view: "https://google.com",
    svg: true,
    icons: ["nuxt", "node", "postgres"],
  },
  {
    coverImg: "https://imgur.com/WNmG3Q6.jpg",
    alt: "default portfolio image",
    heading: "Sadie's Faves 2",
    body: "Lorem ipsum dolor sit amet, word and some adipiscing elit. Lorem ipsum dolor sit amet, word and some adipiscing elit.",
    gitHubLink: "https://github.com/jaminwebdev",
    readMore: "https://google.com",
    view: "https://google.com",
    svg: true,
    icons: ["next", "node", "mongo"],
  },
  {
    coverImg: "https://imgur.com/WNmG3Q6.jpg",
    alt: "default portfolio image",
    heading: "Sadie's Faves 3",
    body: "Lorem ipsum dolor sit amet, word and some adipiscing elit. Lorem ipsum dolor sit amet, word and some adipiscing elit.",
    gitHubLink: "https://github.com/jaminwebdev",
    readMore: "https://google.com",
    view: "https://google.com",
    svg: true,
    icons: ["nuxt", "node", "postgres"],
  },
]
